apiVersion: build.knative.dev/v1alpha1
kind: Build
metadata:
  name: helloword-go-service-build
spec:
  serviceAccountName: build-bot
  source:
    git:
      url: https://github.com/stijnkoopal/knative-test.git
      revision: master
  template:
    name: kaniko
    arguments:
      - name: IMAGE
        value: eu.gcr.io/stijn-koopal-speeltuin/helloworld-go